### ISSUE TITLE
Make text on inactive tabs readable

### ISSUE THREAD

**Issue by garth** [trevordmiller/nova-atom-ui#14]
Text on inactive tabs (even in the demo screenshot) is very hard to read. I'm no designer, but the following fixed it for me.

```css
.tab-bar {
  .tab {
    color: rgba(0, 0, 0, 0.8);
  }
}
```
